import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CPXMate generator",
  description: "Generated by minseongkim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-w-[1440px] max-w-[1920px] px-20 mx-auto bg-white">
        {children}
      </body>
    </html>
  );
}
